# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(choices=[("user", "User"), ("admin", "Admin")], default="user", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(default="INR", max_length=8),
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(choices=[("system", "System"), ("light", "Light"), ("dark", "Dark")], default="dark", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="notifications_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
