# Generated by Codex on 2026-05-26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="target_date",
            new_name="deadline",
        ),
        migrations.AddField(
            model_name="goal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelOptions(
            name="goal",
            options={"ordering": ["deadline", "-created_at"]},
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(fields=["user", "deadline"], name="goals_goal_user_id_b7695d_idx"),
        ),
    ]
